apiVersion: v1
data:
  htpasswd: YWRtaW46JDJhJDEyJDNGRjJtTE5LWWpqS1RjelNoZ1d0WC5seXVNNEFTYnFvSk93WHlsdFdGcnZVTEFQLlB3Sjd1Cg==
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
